const cfg = window.HR_CONFIG || {};
let sb = null;
let state = { session:null, profile:null, view:'dashboard', employees:[], contracts:[], leave:[], warnings:[], companies:[], branches:[], departments:[], positions:[] };
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate = d => d ? new Date(d+'T00:00:00').toLocaleDateString('id-ID') : '-';
const daysUntil = d => d ? Math.ceil((new Date(d+'T00:00:00')-new Date())/86400000) : null;
function configured(){return cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('PASTE_') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('PASTE_')}
async function init(){
  if(!configured()){renderConfigHelp();return}
  sb = window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
  const {data:{session}} = await sb.auth.getSession();
  state.session=session;
  sb.auth.onAuthStateChange((_e,s)=>{state.session=s; if(s) loadProfile(); else renderLogin()});
  if(session) await loadProfile(); else renderLogin();
}
function renderConfigHelp(){document.querySelector('#app').innerHTML=`<div class="login"><div class="login-card"><div class="brand">HR Employee System</div><div class="subtitle">Konfigurasi Supabase belum diisi.</div><p class="muted">Buka <b>config.js</b>, lalu isi SUPABASE_URL dan SUPABASE_ANON_KEY dari project Supabase Anda.</p></div></div>`}
function renderLogin(msg=''){document.querySelector('#app').innerHTML=`<div class="login"><form class="login-card" id="loginForm"><div class="brand">HR Employee System</div><div class="subtitle">Employee Database & HR Tracking</div><div class="field"><label>Email</label><input id="email" type="email" required value=""></div><div class="field"><label>Password</label><input id="password" type="password" required></div>${msg?`<div class="error">${esc(msg)}</div>`:''}<button class="btn btn-primary btn-block">Masuk</button></form></div>`;$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error) renderLogin(error.message)});}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('*').eq('id',state.session.user.id).maybeSingle();if(error||!data){renderLogin('Profil admin belum terdaftar. Pastikan akun Anda sudah dibuat di Supabase.');return}state.profile=data;await loadAll();renderApp()}
async function loadAll(){
  const queries=await Promise.all([
    sb.from('employees').select('*, companies(name), branches(name), departments(name), positions(name)').order('full_name'),
    sb.from('contracts').select('*').order('end_date',{ascending:true}),
    sb.from('leave_requests').select('*, employees(full_name)').order('start_date',{ascending:false}),
    sb.from('warnings').select('*, employees(full_name)').order('issue_date',{ascending:false}),
    sb.from('companies').select('*').order('name'),sb.from('branches').select('*').order('name'),sb.from('departments').select('*').order('name'),sb.from('positions').select('*').order('name')
  ]);
  state.employees=queries[0].data||[];state.contracts=queries[1].data||[];state.leave=queries[2].data||[];state.warnings=queries[3].data||[];state.companies=queries[4].data||[];state.branches=queries[5].data||[];state.departments=queries[6].data||[];state.positions=queries[7].data||[];
}
function renderApp(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="logo">HR Employee System</div><div class="nav">${['dashboard','employees','contracts','leave','warnings','master'].map(v=>`<button class="${state.view===v?'active':''}" data-view="${v}">${({dashboard:'Dashboard',employees:'Karyawan',contracts:'Kontrak',leave:'Cuti',warnings:'Teguran / SP',master:'Master Data'})[v]}</button>`).join('')}</div></aside><main class="main"><div class="topbar"><h1>${title()}</h1><div class="userbox"><span>${esc(state.profile.full_name||state.session.user.email)}</span><span class="avatar">${esc((state.profile.full_name||'A')[0].toUpperCase())}</span><button id="logout" class="btn btn-light">Keluar</button></div></div><div id="content"></div></main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderApp()});$('#logout').onclick=async()=>{await sb.auth.signOut()};renderView()}
function title(){return {dashboard:'Dashboard',employees:'Database Karyawan',contracts:'Kontrak Karyawan',leave:'Cuti Karyawan',warnings:'Surat Teguran / SP',master:'Master Data'}[state.view]}
function renderView(){if(state.view==='dashboard') return dashboard();if(state.view==='employees') return employees();if(state.view==='contracts') return contracts();if(state.view==='leave') return leave();if(state.view==='warnings') return warnings();master()}
function dashboard(){const active=state.employees.filter(e=>e.employment_status==='active').length;const exp=state.contracts.filter(c=>{const n=daysUntil(c.end_date);return c.status==='active'&&n!==null&&n>=0&&n<=30}).length;const onleave=state.leave.filter(l=>l.status==='approved'&&new Date(l.start_date)<=new Date()&&new Date(l.end_date)>=new Date()).length;const warn=state.warnings.filter(w=>w.status==='active').length;$('#content').innerHTML=`<div class="cards"><div class="card"><div class="muted">Karyawan Aktif</div><div class="metric">${active}</div></div><div class="card"><div class="muted">Kontrak ≤ 30 Hari</div><div class="metric">${exp}</div></div><div class="card"><div class="muted">Sedang Cuti</div><div class="metric">${onleave}</div></div><div class="card"><div class="muted">Teguran Aktif</div><div class="metric">${warn}</div></div></div><div class="section"><div class="section-head"><h2>Perusahaan</h2></div><div class="cards">${state.companies.map(c=>`<div class="card"><div class="muted">${esc(c.name)}</div><div class="metric">${state.employees.filter(e=>e.company_id===c.id).length}</div><div class="muted">karyawan</div></div>`).join('')}</div></div><div class="section"><div class="section-head"><h2>Karyawan Terbaru</h2><button class="btn btn-primary" onclick="showEmployeeForm()">+ Tambah Karyawan</button></div>${employeeTable(state.employees.slice(0,8))}</div>`}
function employeeTable(rows){if(!rows.length)return '<div class="card empty">Belum ada data karyawan.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Nama</th><th>Perusahaan</th><th>Outlet</th><th>Jabatan</th><th>Status</th><th>Mulai</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.employee_number)}</td><td><b>${esc(e.full_name)}</b><div class="muted">${esc(e.email||'')}</div></td><td>${esc(e.companies?.name||'-')}</td><td>${esc(e.branches?.name||'-')}</td><td>${esc(e.positions?.name||'-')}</td><td><span class="badge ${e.employment_status==='active'?'badge-green':'badge-yellow'}">${esc(e.employment_status)}</span></td><td>${fmtDate(e.join_date)}</td></tr>`).join('')}</tbody></table></div>`}
function employees(){const html=`<div class="toolbar"><input id="empSearch" placeholder="Cari nama / ID / NIK..."><select id="companyFilter"><option value="">Semua perusahaan</option>${state.companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><button class="btn btn-primary" onclick="showEmployeeForm()">+ Tambah Karyawan</button></div><div class="section" id="empTable"></div>`;$('#content').innerHTML=html;const draw=()=>{let q=$('#empSearch').value.toLowerCase(),co=$('#companyFilter').value;let rows=state.employees.filter(e=>(!q||[e.full_name,e.employee_number,e.nik].join(' ').toLowerCase().includes(q))&&(!co||e.company_id===co));$('#empTable').innerHTML=employeeTable(rows)};$('#empSearch').oninput=draw;$('#companyFilter').onchange=draw;draw()}
function contracts(){let rows=state.contracts;$('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Daftar Kontrak</h2></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Karyawan</th><th>No. Kontrak</th><th>Jenis</th><th>Mulai</th><th>Berakhir</th><th>Status</th></tr></thead><tbody>${rows.map(c=>{const n=daysUntil(c.end_date);let cls=n!==null&&n<=30?'badge-red':'badge-green';return `<tr><td>${esc(state.employees.find(e=>e.id===c.employee_id)?.full_name||'-')}</td><td>${esc(c.contract_number||'-')}</td><td>${esc(c.contract_type)}</td><td>${fmtDate(c.start_date)}</td><td>${fmtDate(c.end_date)} ${n!==null?`<span class="badge ${cls}">${n<0?'Lewat':n+' hari'}</span>`:''}</td><td>${esc(c.status)}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="card empty">Belum ada kontrak.</div>'}</div>`}
function leave(){const rows=state.leave;$('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Riwayat Cuti</h2></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Karyawan</th><th>Periode</th><th>Hari</th><th>Alasan</th><th>Status</th></tr></thead><tbody>${rows.map(l=>`<tr><td>${esc(l.employees?.full_name||'-')}</td><td>${fmtDate(l.start_date)} - ${fmtDate(l.end_date)}</td><td>${esc(l.total_days)}</td><td>${esc(l.reason||'-')}</td><td><span class="badge ${l.status==='approved'?'badge-green':l.status==='pending'?'badge-yellow':'badge-red'}">${esc(l.status)}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">Belum ada pengajuan cuti.</div>'}</div>`}
function warnings(){const rows=state.warnings;$('#content').innerHTML=`<div class="section"><div class="section-head"><h2>Surat Teguran / SP</h2></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Karyawan</th><th>Jenis</th><th>Nomor</th><th>Tanggal</th><th>Perihal</th><th>Status</th></tr></thead><tbody>${rows.map(w=>`<tr><td>${esc(w.employees?.full_name||'-')}</td><td>${esc(w.warning_type)}</td><td>${esc(w.warning_number||'-')}</td><td>${fmtDate(w.issue_date)}</td><td>${esc(w.title)}</td><td><span class="badge ${w.status==='active'?'badge-red':'badge-yellow'}">${esc(w.status)}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">Belum ada surat teguran.</div>'}</div>`}
function master(){$('#content').innerHTML=`<div class="cards"><div class="card"><b>Perusahaan</b><div class="metric">${state.companies.length}</div><div class="muted">It's My Cake & Zayco Boga Alifa sudah tersedia.</div></div><div class="card"><b>Outlet</b><div class="metric">${state.branches.length}</div></div><div class="card"><b>Departemen</b><div class="metric">${state.departments.length}</div></div><div class="card"><b>Jabatan</b><div class="metric">${state.positions.length}</div></div></div><div class="section card"><b>Perusahaan</b><div class="section" style="display:grid;gap:8px">${state.companies.map(c=>`<div>${esc(c.name)} <span class="badge badge-green">Aktif</span></div>`).join('')}</div></div>`}
window.showEmployeeForm=()=>{const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal"><div class="section-head"><h2>Tambah Karyawan</h2><button class="btn btn-light" id="close">Tutup</button></div><form id="empForm"><div class="modal-grid"><div class="field"><label>ID Karyawan *</label><input name="employee_number" required></div><div class="field"><label>Nama Lengkap *</label><input name="full_name" required></div><div class="field"><label>NIK</label><input name="nik"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>No. HP</label><input name="phone"></div><div class="field"><label>Tanggal Masuk *</label><input name="join_date" type="date" required></div><div class="field"><label>Perusahaan *</label><select name="company_id" required><option value="">Pilih</option>${state.companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Outlet</label><select name="branch_id"><option value="">Pilih</option>${state.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Departemen</label><select name="department_id"><option value="">Pilih</option>${state.departments.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>Jabatan</label><select name="position_id"><option value="">Pilih</option>${state.positions.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="employment_status"><option value="active">Aktif</option><option value="inactive">Tidak Aktif</option></select></div><div class="field"><label>Tipe</label><select name="employment_type"><option value="permanent">Tetap</option><option value="contract">Kontrak</option><option value="intern">Intern</option><option value="part_time">Part Time</option><option value="daily">Harian</option></select></div></div><div class="modal-actions"><button type="button" class="btn btn-light" id="cancel">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div>`;document.body.appendChild(modal);$('#close').onclick=$('#cancel').onclick=()=>modal.remove();$('#empForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),obj=Object.fromEntries(f.entries());Object.keys(obj).forEach(k=>{if(obj[k]==='')obj[k]=null});obj.employment_status=obj.employment_status||'active';const {error}=await sb.from('employees').insert(obj);if(error){alert(error.message);return}modal.remove();await loadAll();renderApp()}};
init();
